### PR TITLE
It seems like this whole module is completely out of use? Right?

### PR DESCRIPTION
**Pull request by novakboskov**
- There is no tests so I can't check necessity of this module.
- By reading the code I've inferred that core/repository is replaced
  with porter/repository module.

### CODE REVIEW

**Comment by lazer-nikolic** [comment]
You can also delete core/project so we don't make two separate pull requests.

**Comment by novakboskov** [comment]
Can you check if recent deletions are also OK?

**Comment by lazer-nikolic** [comment]
Seems fine.

**Comment by novakboskov** [comment]
OK, I'll merge it later tonight when I complete fixing #28.

**Comment by novakboskov** [comment]
I'll reuse this PR to discuss all the possible cleanups I'm finding these days.

Take a look at `core/forms.py` deletion. Do we have any particular reason to do this that way or it's OK to do standard(automatic) form->model binding?
I've also found that it didn't worked due to `form.is_valid()` was `False` (at least when I get there through the dashboard)

**Comment by lazer-nikolic** [comment]
If you're talking about IssueForm, It should be safe to delete. It is a leftover from when we transitioned to the new URL structure. Before that, issue had a select box to choose repository it belongs to. In order to keep both issue forms working: one that is implicitly tied to a repository through path, and one that is explicitly assigned with a select box, we dynamically changed displayed fields.

**Pull request merged**
